### ISSUE TITLE
`ValueError: images do not match`

### ISSUE THREAD

**Issue by BTWS2** [BTWS2/judge-turtle#30]
- [x] https://github.ugent.be/brewille/oef_turtle/tree/master/custom_canvas
- [x] https://naos.ugent.be/nl/submissions/983379/
- [x] https://naos.ugent.be/nl/submissions/983378/
- [x] https://naos.ugent.be/nl/submissions/983377/

```python
import turtle

center = (0, 0)
side = 50

turtle.fillcolor("blue")
x_pt, y_pt = center

x_pt -= side / 2
y_pt += side / 2

turtle.up()
turtle.goto(x_pt, y_pt)
turtle.down()

turtle.begin_fill()
for _ in range(4):
    turtle.forward(side)
    turtle.right(90)
turtle.end_fill()

turtle.home()
turtle.dot(5)


turtle.done()
```

```python
Standard Error:
Traceback (most recent call last):
  File "/mnt/_n9h4GBuCwjJb87ulQw3cg/judge/turtle_judge.py", line 74, in <module>
    correct_pixels, total_pixels = diff_images(png_submission, png_solution)
  File "/mnt/_n9h4GBuCwjJb87ulQw3cg/judge/judge/runtime.py", line 61, in diff_images
    diff = ImageChops.difference(image1, image2)
  File "/usr/local/lib/python3.10/site-packages/PIL/ImageChops.py", line 102, in difference
    return image1._new(image1.im.chop_difference(image2.im))
ValueError: images do not match
```

**Comment by inteon** [comment]
fixed in 2dc0be658eb95d74b12177c247fb147106e258a4
